parameters:
#    ldc_article.example.class: Ldc\ArticleBundle\Example

services:
#    ldc_article.example:
#        class: %ldc_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
