# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
WmsIntroductionBundle:
    resource: "@WmsIntroductionBundle/Resources/config/routing.yml"
    prefix: /wms