# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
WmsIntroductionBundle:
    resource: "@WmsIntroductionBundle/Resources/config/routing.yml"
    prefix: /wms

#======== ==================== ====================       
# ---------------- ROUTES POUR LDC
#======== ==================== ====================      

#======== SIte web
LdcWebsiteBundle:
    resource: "@LdcWebsiteBundle/Resources/config/routing.yml"
    prefix: /ldc

#======== Utilisateurs
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#======== Back office
LdcWebsiteBundle_admin:
    resource: "@LdcWebsiteBundle/Resources/config/routing_admin.yml"
    prefix: /ldc/admin/

LdcArticleBundle_admin:
    resource: "@LdcArticleBundle/Resources/config/routing_admin.yml"
    prefix: /ldc/admin/article

LdcEventBundle_admin:
    resource: "@LdcEventBundle/Resources/config/routing_admin.yml"
    prefix: /ldc/admin/event

LdcSliderImageBundle_admin:
    resource: "@LdcSliderImageBundle/Resources/config/routing_admin.yml"
    prefix: /ldc/admin/slider

LdcUserBundle_admin:
    resource: "@LdcUserBundle/Resources/config/routing_admin.yml"
    prefix: /ldc/admin/user