jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    access_denied_url: ldc/unauthorized

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/ldc$
            security: false

        main:
            access_denied_url: ldc/unauthorized
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                remember_me: true            # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
                success_handler: authentication_handler
                failure_handler: authentication_handler
            logout:
                success_handler: authentication_handler
            anonymous:    true
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
    access_control:
        - { path: /admin, roles: ROLE_ADMIN }
        - { path: /admin/user, roles: ROLE_SUPER_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
