ldcsliderimagebundle_new:
    pattern: /new
    defaults: { _controller: LdcSliderImageBundle:SliderImageAdmin:new}

ldcsliderimagebundle_edit:
    pattern: /edit/{id}
    defaults: { _controller: LdcSliderImageBundle:SliderImageAdmin:edit}

ldcsliderimagebundle_list:
    pattern: /list
    defaults: { _controller: LdcSliderImageBundle:SliderImageAdmin:list}

ldcsliderimagebundle_confirmed:
    pattern: /confirmed
    defaults: { _controller: LdcSliderImageBundle:SliderImageAdmin:confirmed}