parameters:
#    ldc_event.example.class: Ldc\EventBundle\Example

services:
#    ldc_event.example:
#        class: %ldc_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
