<?php

namespace Ldc\SurveyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SurveyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyRepository extends EntityRepository
{
	public function getLastSurvey()
	{
		$qb = $this->createQueryBuilder("s");
		$qb->orderBy("s.date_created","desc");
		$q = $qb->getQuery();

		$q->setMaxResults(1);
		
		return $q->getOneOrNullResult();
	}
	
	public function countAll()
	{
		return $this->createQueryBuilder("s")
			->select('COUNT(s)')
			->getQuery()
			->getSingleScalarResult();
	}
}