<?php

namespace Ldc\SliderImageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SliderImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderImageRepository extends EntityRepository
{
}