<?php

namespace Ldc\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SliderImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{		
	public function getLastUser()
	{
		$qb = $this->createQueryBuilder("u");
		$qb->orderBy("u.register_date","desc");
		$q = $qb->getQuery();
		
		$q->setFirstResult(1);
		$q->setMaxResults(1);
		
		return $q->getOneOrNullResult();
	}
	
	public function countAll()
	{
		return $this->createQueryBuilder('u')
		 ->select('COUNT(u)')
		 ->getQuery()
		 ->getSingleScalarResult();
	}
}