# # # # ----------- Website ----------- # # # # 
ldcwebsitebundle_accueil:
    pattern:  /
    defaults: { _controller: LdcWebsiteBundle:Website:index }

# # # # ----------- Users ----------- # # # # 
ldcwebsitebundle_usersprofile:
    pattern:  users/profile/{id}
    defaults: { _controller: LdcWebsiteBundle:User:profile}

# # # # ----------- Articles ----------- # # # # 
ldcwebsitebundle_articles:
    pattern: articles/{page}
    defaults: { _controller: LdcWebsiteBundle:Article:index }

ldcwebsitebundle_articlesshow:
    pattern: articles/show/{id}
    defaults: { _controller: LdcWebsiteBundle:Article:show }

# # # # ----------- Evenements ----------- # # # # 
ldcwebsitebundle_events:
    pattern: events
    defaults: { _controller: LdcWebsiteBundle:Event:index }

# # # # ----------- Sondages ----------- # # # # 
ldcwebsitebundle_surveys:
    pattern: surveys
    defaults: { _controller: LdcWebsiteBundle:Survey:index }



# # # # ----------- Erreurs ----------- # # # # 
ldcwebsitebundle_unhautorized:
    pattern:  /unauthorized
    defaults: { _controller: LdcWebsiteBundle:Website:unauthorized }