parameters:
#    ldc_website.example.class: Ldc\WebsiteBundle\Example

services:
    ldc_website_extension:
        class: Ldc\WebsiteBundle\Twig\Extensions\LdcWebsiteExtension
        tags:
            -  { name: twig.extension }
