parameters:
#    ldc_website.example.class: Ldc\WebsiteBundle\Example

services:
#    ldc_website.example:
#        class: %ldc_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
